### ISSUE TITLE
[Bug] Missing `table_l.py`

### ISSUE THREAD

**Issue by shenzhiy21** [HKUSTDial/HAIChart#9]
Hello,

I’m attempting to reproduce your results, but I encountered an issue while setting up the environment according to the instructions provided in `README.md`.

Here is the error message I received:

```
Traceback (most recent call last):
  File "haichart.py", line 10, in <module>
    import tools
  File "/data/workspace/HAIChart/tools/__init__.py", line 14, in <module> 
    from .table_l import Table as Table_LTR  # table of Learning-to-rank model
ModuleNotFoundError: No module named 'tools.table_l'
```

It seems like the file `table_l.py` is missing from the repository. Could you please assist me in resolving this issue?

BTW, I noticed that the `pyecharts` package should be added to the `requirements.txt` file, as it was not included.

Thank you for your support!

**Comment by xypkent** [comment]
Thank you for your detailed feedback and for bringing this issue to our attention.

Regarding the missing table_l.py file: The table_l module is based on our lab's work on DeepEye, which you can find here: [DeepEye-APIs](https://github.com/HKUSTDial/DeepEye-APIs). You may refer to this repository for now, and we will update the missing content in this repository soon. I'll notify you as soon as the update is available.

For the pyecharts package: Thank you for your suggestion. We will add it to the requirements.txt to ensure a smoother setup process for other users as well.

Please let us know if you encounter any other issues or need further assistance. We appreciate your patience and support!

**Comment by shenzhiy21** [comment]
Thanks for your help!

Another issue encountered:

```
Traceback (most recent call last):
  File "haichart.py", line 11, in <module>
    from mcgs import MCGS, Node
  File "/data/workspace/HAIChart/mcgs.py", line 12, in <module>
    from state import State
ModuleNotFoundError: No module named 'state'
```

`state.py` missing as well.

**Comment by xypkent** [comment]
Hi Zhiyang,

Thank you for your detailed feedback. We've just updated the code in the repository to address the missing files.

Given the complexity of the project and the dependencies across multiple modules, we are planning to package everything in a more streamlined format for easier deployment in the near future. This should make it more convenient for users to set up and use the system without running into missing module issues.
